#!/usr/bin/env python

import os
import subprocess

my_env = os.environ.copy()
my_env["PATH"] = "/usr/local/bin:/usr/local/sbin:" + my_env["PATH"]

os.chdir(subprocess.check_output(['git', "rev-parse", "--show-toplevel"]).strip())

commit_filenames = subprocess.check_output(["git", "diff-index", "--name-only", "--diff-filter=ACM", "--cached", "HEAD", "--"]).strip().split("\n")
failed_filenames = []

# jshint each file that ends in .js
for file_name in commit_filenames:
    if file_name[-3:] == ".js":
        # Return code of 0 means everything passed jshint validation
        if subprocess.call(['node_modules/jshint/bin/jshint', "--config=.jshintrc", file_name], env=my_env) != 0:
            print # extra newline makes it look nicer
            failed_filenames.append(file_name)

if failed_filenames:
    for file_name in failed_filenames:
        print file_name + " failed jshint"
    print "\nAborting commit"
    exit(1)
